"""Lane Crosser -- a Frogger-style game showcasing the engine's collision
system, asset/animation system, and scene-management features together.

- Collision: AABBCollider layers/masks distinguish safe contact (logs,
  goals) from deadly contact (cars), and enter/exit callbacks drive both
  the log-riding mechanic and goal scoring.
- Assets and animation: real PNG sprite sheets (generated by
  generate_lane_crosser_assets.py) loaded through AssetManager, sliced into
  named regions by SpriteAtlas, and played back with independent
  AnimationClip instances (the frog's hop, each log's bob).
- Scene management: a named scene registry (menu/game/game_over/pause), a
  pushed pause overlay that freezes gameplay underneath it, and a
  persistent PlayerProgress object that survives every level-up scene
  replacement without resetting or restarting.
"""

from pathlib import Path
import random

from engine import (
    AABBCollider,
    AnimationClip,
    Collider,
    GameEngine,
    GameObject,
    Scene,
    Sprite,
    SpriteAtlas,
    Vector2,
)

WIDTH, HEIGHT = 800, 600

FROG_STEP_X = 40
FROG_STEP_Y = 50
FROG_MIN_X, FROG_MAX_X = 20, 780

GOAL_Y = 75
RIVER_YS = (125, 175, 225, 275)
MEDIAN_Y = 325
ROAD_YS = (375, 425, 475, 525)
START_Y = 575
START_POSITION = Vector2(400, START_Y)
GOAL_XS = (160, 280, 400, 520, 640)

LAYER_FROG = 1 << 0
LAYER_CAR = 1 << 1
LAYER_LOG = 1 << 2
LAYER_GOAL = 1 << 3

LIVES_START = 3


# --- Persistent game state -------------------------------------------------


class PlayerProgress(GameObject):
    """Score, lives, and level. Marked persistent so it survives every
    level-up scene replacement instead of being recreated from scratch."""

    def __init__(self):
        super().__init__('PlayerProgress')
        self.set_persistent()
        self.score = 0
        self.lives = LIVES_START
        self.level = 1

    def reset(self):
        self.score = 0
        self.lives = LIVES_START
        self.level = 1


# --- Lane background (drawn first, via z-order) -----------------------------


class LaneBackground(GameObject):
    """Static striped background for every lane. Pure custom rendering, no
    sprite component -- exists purely to demonstrate z-ordering."""

    def __init__(self):
        super().__init__('LaneBackground')
        self.z_order = -10

    def render(self, renderer):
        renderer.draw_rectangle(Vector2(WIDTH / 2, GOAL_Y), Vector2(WIDTH, FROG_STEP_Y), '#123028')
        for y in RIVER_YS:
            renderer.draw_rectangle(Vector2(WIDTH / 2, y), Vector2(WIDTH, FROG_STEP_Y), '#16324A')
        renderer.draw_rectangle(Vector2(WIDTH / 2, MEDIAN_Y), Vector2(WIDTH, FROG_STEP_Y), '#1E3320')
        for y in ROAD_YS:
            renderer.draw_rectangle(Vector2(WIDTH / 2, y), Vector2(WIDTH, FROG_STEP_Y), '#2A2A2A')
        renderer.draw_rectangle(Vector2(WIDTH / 2, START_Y), Vector2(WIDTH, FROG_STEP_Y), '#1E3320')


# --- The frog ----------------------------------------------------------------


class Frog(GameObject):
    """Player character. Hops in discrete grid steps, rides logs it lands
    on, and dies on contact with a car or by drowning in the river."""

    def __init__(self, atlas, hop_clip):
        super().__init__('Frog')
        self.sprite = self.add_component(Sprite(size=Vector2(32, 32)))
        self.sprite.set_sprite_atlas(atlas, 'idle')
        self.sprite.add_animation_clip(hop_clip, on_complete=self._finish_hop)

        self.collider = self.add_component(
            AABBCollider(Vector2(24, 24), layer=LAYER_FROG, mask=LAYER_CAR | LAYER_LOG | LAYER_GOAL)
        )
        self.collider.on_enter(self._on_collision)
        self.collider.on_exit(self._on_separation)

        self.current_log = None
        self.transform.position = START_POSITION.copy()

    def respawn(self):
        self.transform.position = START_POSITION.copy()
        self.current_log = None
        self.sprite.set_current_sprite('idle')

    def _finish_hop(self):
        self.sprite.set_current_sprite('idle')

    def _on_collision(self, other: Collider):
        if other.layer == LAYER_CAR:
            self._die()
        elif other.layer == LAYER_LOG:
            self.current_log = other.game_object

    def _on_separation(self, other: Collider):
        if other.layer == LAYER_LOG and other.game_object is self.current_log:
            self.current_log = None

    def _die(self):
        if hasattr(self.scene, 'on_frog_died'):
            self.scene.on_frog_died()

    def _in_river(self) -> bool:
        return any(abs(self.transform.position.y - y) < 1.0 for y in RIVER_YS)

    def hop(self, dx: float, dy: float):
        position = self.transform.position
        new_position = Vector2(
            max(FROG_MIN_X, min(FROG_MAX_X, position.x + dx)),
            max(GOAL_Y, min(START_Y, position.y + dy)),
        )
        if new_position == position:
            return
        self.transform.position = new_position
        self.current_log = None
        self.sprite.play_animation('hop', reset=True)

    def update(self, delta_time: float):
        super().update(delta_time)

        if self.current_log is not None:
            self.transform.position.x += self.current_log.velocity.x * delta_time
            self.transform.position.x = max(FROG_MIN_X, min(FROG_MAX_X, self.transform.position.x))

        if self._in_river() and self.current_log is None:
            self._die()
            return

        if not hasattr(self.scene, 'engine'):
            return
        input_manager = self.scene.engine.input_manager
        if input_manager.is_key_just_pressed('up') or input_manager.is_key_just_pressed('w'):
            self.hop(0, -FROG_STEP_Y)
        elif input_manager.is_key_just_pressed('down') or input_manager.is_key_just_pressed('s'):
            self.hop(0, FROG_STEP_Y)
        elif input_manager.is_key_just_pressed('left') or input_manager.is_key_just_pressed('a'):
            self.hop(-FROG_STEP_X, 0)
        elif input_manager.is_key_just_pressed('right') or input_manager.is_key_just_pressed('d'):
            self.hop(FROG_STEP_X, 0)


# --- Hazards and helpers ------------------------------------------------------


class Car(GameObject):
    """A road hazard. Wraps around the screen; kills the frog on contact."""

    def __init__(self, atlas, sprite_name, y, speed):
        super().__init__('Car')
        self.velocity = Vector2(speed, 0)
        self.sprite = self.add_component(Sprite(size=Vector2(48, 28)))
        self.sprite.set_sprite_atlas(atlas, sprite_name)
        self.add_component(AABBCollider(Vector2(40, 20), layer=LAYER_CAR, mask=LAYER_FROG))
        self.transform.position = Vector2(0, y)

    def update(self, delta_time: float):
        super().update(delta_time)
        self.transform.position.x += self.velocity.x * delta_time
        if self.velocity.x > 0 and self.transform.position.x > WIDTH + 40:
            self.transform.position.x = -40
        elif self.velocity.x < 0 and self.transform.position.x < -40:
            self.transform.position.x = WIDTH + 40


class Log(GameObject):
    """A river hazard the frog can safely ride. Wraps around the screen."""

    def __init__(self, atlas, clip, y, speed, phase=0.0):
        super().__init__('Log')
        self.velocity = Vector2(speed, 0)
        self.sprite = self.add_component(Sprite(size=Vector2(96, 28)))
        self.sprite.set_sprite_atlas(atlas, 'bob_0')
        self.sprite.add_animation_clip(clip)
        self.sprite.play_animation('bob')
        if phase:
            self.sprite.update(phase)
        self.add_component(AABBCollider(Vector2(96, 20), layer=LAYER_LOG, mask=LAYER_FROG))
        self.transform.position = Vector2(0, y)

    def update(self, delta_time: float):
        super().update(delta_time)
        self.transform.position.x += self.velocity.x * delta_time
        if self.velocity.x > 0 and self.transform.position.x > WIDTH + 60:
            self.transform.position.x = -60
        elif self.velocity.x < 0 and self.transform.position.x < -60:
            self.transform.position.x = WIDTH + 60


class GoalSlot(GameObject):
    """A lily-pad slot at the top of the screen. Claims itself the first
    time the frog reaches it and reports back to the scene."""

    def __init__(self, atlas, x):
        super().__init__('GoalSlot')
        self.is_filled = False
        self.sprite = self.add_component(Sprite(size=Vector2(56, 48)))
        self.sprite.set_sprite_atlas(atlas, 'empty')
        self.add_component(AABBCollider(Vector2(56, 48), layer=LAYER_GOAL, mask=LAYER_FROG)).on_enter(
            self._on_frog_arrived
        )
        self.transform.position = Vector2(x, GOAL_Y)

    def _on_frog_arrived(self, other: Collider):
        if self.is_filled:
            return
        self.is_filled = True
        self.sprite.set_current_sprite('filled')
        if hasattr(self.scene, 'on_goal_filled'):
            self.scene.on_goal_filled()


# --- Scenes -------------------------------------------------------------------


class MenuScene(Scene):
    def __init__(self):
        super().__init__('Menu')

    def on_initialize(self):
        pass

    def update(self, delta_time: float):
        super().update(delta_time)
        if not hasattr(self, 'engine'):
            return
        if self.engine.input_manager.is_key_just_pressed('space'):
            self.engine.start_new_game()


class GameScene(Scene):
    def __init__(self, level: int):
        super().__init__('Game')
        self.level = level
        self.progress = None
        self.goal_slots = []

    def on_initialize(self):
        existing = self.find_object('PlayerProgress')
        if existing is not None:
            self.progress = existing
        else:
            self.progress = PlayerProgress()
            self.add_object(self.progress)
        self.progress.level = self.level

        self.add_object(LaneBackground())

        assets = self.engine.assets
        speed_multiplier = 1.0 + (self.level - 1) * 0.15

        for index, y in enumerate(ROAD_YS):
            direction = 1 if index % 2 == 0 else -1
            speed = direction * (70 + index * 15) * speed_multiplier
            color = 'red' if index % 2 == 0 else 'blue'
            facing = 'right' if direction > 0 else 'left'
            spacing = WIDTH / 3
            for slot in range(3):
                car = Car(assets.cars, f'{color}_{facing}', y, speed)
                car.transform.position.x = slot * spacing + index * 40
                self.add_object(car)

        for index, y in enumerate(RIVER_YS):
            direction = 1 if index % 2 == 0 else -1
            speed = direction * (50 + index * 10) * speed_multiplier
            spacing = WIDTH / 2
            for slot in range(2):
                log = Log(assets.logs, assets.log_bob_clip, y, speed, phase=slot * 0.4)
                log.transform.position.x = slot * spacing + index * 60
                self.add_object(log)

        self.goal_slots = [GoalSlot(assets.goals, x) for x in GOAL_XS]
        for goal in self.goal_slots:
            self.add_object(goal)

        self.frog = Frog(assets.frog, assets.frog_hop_clip)
        self.add_object(self.frog)

    def on_goal_filled(self):
        self.progress.score += 100
        self.frog.respawn()
        if all(goal.is_filled for goal in self.goal_slots):
            self.progress.score += 500
            self.progress.level += 1
            self.engine.register_scene('game', lambda: GameScene(self.progress.level), replace=True)
            self.engine.load_scene('game')

    def on_frog_died(self):
        self.progress.lives -= 1
        if self.progress.lives <= 0:
            self.engine.load_scene('game_over')
        else:
            self.frog.respawn()

    def update(self, delta_time: float):
        super().update(delta_time)
        if not hasattr(self, 'engine'):
            return
        if self.engine.input_manager.is_key_just_pressed('escape'):
            self.engine.push_scene('pause')


class PauseScene(Scene):
    def __init__(self):
        super().__init__('Pause')

    def on_initialize(self):
        pass

    def update(self, delta_time: float):
        super().update(delta_time)
        if not hasattr(self, 'engine'):
            return
        if self.engine.input_manager.is_key_just_pressed('escape'):
            self.engine.pop_scene()

    def render(self, renderer):
        super().render(renderer)
        renderer.draw_rectangle(Vector2(WIDTH / 2, HEIGHT / 2), Vector2(320, 140), '#101018', outline='#FFFF00', width=2)
        renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2 - 20), 'PAUSED', '#FFFF00', 28, 'center')
        renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2 + 15), 'Press ESC to resume', '#FFFFFF', 14, 'center')


class GameOverScene(Scene):
    def __init__(self):
        super().__init__('GameOver')

    def on_initialize(self):
        pass

    def update(self, delta_time: float):
        super().update(delta_time)
        if not hasattr(self, 'engine'):
            return
        if self.engine.input_manager.is_key_just_pressed('space'):
            progress = self.find_object('PlayerProgress')
            if progress is not None:
                progress.set_persistent(False)
            self.engine.load_scene('menu')

    def render(self, renderer):
        super().render(renderer)
        progress = self.find_object('PlayerProgress')
        score = progress.score if progress else 0
        level = progress.level if progress else 1
        renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2 - 40), 'GAME OVER', '#FF4444', 36, 'center')
        renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2), f'Final Score: {score}', '#FFFFFF', 18, 'center')
        renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2 + 30), f'Reached Level: {level}', '#FFFFFF', 16, 'center')
        renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2 + 70), 'Press SPACE for the menu', '#FFE080', 14, 'center')


# --- Engine --------------------------------------------------------------------


class GameAssets:
    """Loads and slices every sprite sheet once, at startup.

    Filenames are resolved by the engine's AssetManager against the
    asset_root passed to LaneCrosserGame, so no path is joined here.
    """

    def __init__(self, asset_manager):
        self.frog = self._load_frog(asset_manager)
        self.frog_hop_clip = AnimationClip.from_frames('hop', ['hop'], frame_duration=0.15, loop=False)

        self.cars = self._load_cars(asset_manager)

        self.logs = self._load_logs(asset_manager)
        self.log_bob_clip = AnimationClip.from_frames('bob', ['bob_0', 'bob_1'], frame_duration=0.4, loop=True)

        self.goals = self._load_goals(asset_manager)

    def _load_frog(self, asset_manager):
        image = asset_manager.load_image('lane_crosser_frog.png')
        atlas = SpriteAtlas(Vector2(64, 32), image)
        atlas.add_sprite('idle', Vector2(0, 0), Vector2(32, 32))
        atlas.add_sprite('hop', Vector2(32, 0), Vector2(32, 32))
        return atlas

    def _load_cars(self, asset_manager):
        image = asset_manager.load_image('lane_crosser_cars.png')
        atlas = SpriteAtlas(Vector2(192, 28), image)
        atlas.add_sprite('red_right', Vector2(0, 0), Vector2(48, 28))
        atlas.add_sprite('red_left', Vector2(48, 0), Vector2(48, 28))
        atlas.add_sprite('blue_right', Vector2(96, 0), Vector2(48, 28))
        atlas.add_sprite('blue_left', Vector2(144, 0), Vector2(48, 28))
        return atlas

    def _load_logs(self, asset_manager):
        image = asset_manager.load_image('lane_crosser_logs.png')
        atlas = SpriteAtlas(Vector2(192, 28), image)
        atlas.add_sprite('bob_0', Vector2(0, 0), Vector2(96, 28))
        atlas.add_sprite('bob_1', Vector2(96, 0), Vector2(96, 28))
        return atlas

    def _load_goals(self, asset_manager):
        image = asset_manager.load_image('lane_crosser_goals.png')
        atlas = SpriteAtlas(Vector2(112, 48), image)
        atlas.add_sprite('empty', Vector2(0, 0), Vector2(56, 48))
        atlas.add_sprite('filled', Vector2(56, 0), Vector2(56, 48))
        return atlas


class LaneCrosserGame(GameEngine):
    """A Frogger-style game demonstrating collision layers, real sprite-sheet
    animation, and named/stacked/persistent scene management together."""

    def __init__(self):
        assets_root = Path(__file__).resolve().parents[1] / 'assets'
        super().__init__('Lane Crosser', (WIDTH, HEIGHT), 60, asset_root=assets_root)

    def initialize(self):
        self.assets = GameAssets(self.asset_manager)
        self.register_scene('menu', MenuScene)
        self.register_scene('pause', PauseScene)
        self.register_scene('game_over', GameOverScene)
        self.load_scene('menu')

        print('Lane Crosser')
        print('Arrow keys or WASD - hop  |  ESC - pause  |  SPACE - start / continue')
        print('Ride the logs, dodge the cars, fill every lily pad to advance.')

    def start_new_game(self):
        self.register_scene('game', lambda: GameScene(1), replace=True)
        self.load_scene('game')

    def update(self, delta_time: float):
        if self.input_manager.is_key_just_pressed('escape') and self.current_scene and self.current_scene.name == 'Menu':
            self.quit()

    def render(self):
        stack = self.scene_manager.scene_stack
        base_scene = stack[0] if stack else None
        progress = base_scene.find_object('PlayerProgress') if base_scene else None

        if base_scene is None or base_scene.name == 'Menu':
            self.renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2 - 60), 'LANE CROSSER', '#33DD66', 40, 'center')
            self.renderer.draw_text(
                Vector2(WIDTH / 2, HEIGHT / 2),
                'Arrow keys or WASD to hop  |  Ride logs, dodge cars, fill every pad',
                '#FFFFFF',
                14,
                'center',
            )
            self.renderer.draw_text(Vector2(WIDTH / 2, HEIGHT / 2 + 40), 'Press SPACE to start', '#FFE080', 18, 'center')
            return

        if progress is not None:
            self.renderer.draw_text(Vector2(90, 25), f'Score: {progress.score:05d}', '#FFFFFF', 14, 'center')
            self.renderer.draw_text(Vector2(WIDTH / 2, 25), f'Level: {progress.level}', '#FFFFFF', 14, 'center')
            self.renderer.draw_text(Vector2(WIDTH - 90, 25), f'Lives: {progress.lives}', '#FFFFFF', 14, 'center')


if __name__ == '__main__':
    LaneCrosserGame().run()
